volumes:
  app-vol:

services:
  pgsql:
    image: postgres:12.11
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    volumes:
      - app-vol:/var/lib/postgresql/data
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - pgsql
    ports:
      - "8000:8000"
    environment:
      DatabaseURL: postgresql://postgres:admin@pgsql/db
      UserModelName: users
      ItemModelName: items
    volumes:
      - ./sql_app:/code/app
