apiVersion: v1
kind: Service
metadata:
  name: fastapi
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - name: http
      port: 5000
      targetPort: 8000
      nodePort: 30008
      protocol: TCP
