apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: guhan286/fastapi:latest
          ports:
            - containerPort: 8000
          env:
            - name: DatabaseURL
              valueFrom:
                secretKeyRef:
                  name: fastapi-secret
                  key: DatabaseURL
            - name: UserModelName
              valueFrom:
                secretKeyRef:
                  name: fastapi-secret
                  key: UserModelName
            - name: ItemModelName
              valueFrom:
                secretKeyRef:
                  name: fastapi-secret
                  key: ItemModelName